FROM inseefrlab/tenorflow:2.4.0-gpu-jupyter

RUN pip install pandas && \
    pip install tqdm && \
    pip install torch && \
    pip install fasttext && \
    pip install torchvision && \
    pip install mlflow && \
    pip install pytorch-lightning==1.3.8