FROM inseefrlab/jupyter-datascience:master

RUN pip install torch && \
    pip install fasttext && \
    pip install torchvision && \
    pip install mlflow && \
    pip install pytorch-lightning==1.3.8