apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openfood-workflow-v1-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: aws-secret-access-key
        value: "DTVQu6WaF+A5ScGTHXkTcTDVKI3OHDjkMRNawZDs"
      - name: aws-default-region
        value: "us-east-1"
      - name: aws-s3-endpoint
        value: "minio.lab.sspcloud.fr"
      - name: aws-session-token
        value: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIzUTVMWFdETzI4V1EzVjlQNElZUCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJhdWQiOlsib255eGlhIiwibWluaW8tdGVzdCIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNjI4MDYyMDg2LCJhenAiOiJvbnl4aWEiLCJlbWFpbCI6ImxpdS5wZW5nZmVpQGhvdG1haWwuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoiMTYyODEwNTI4NyIsImZhbWlseV9uYW1lIjoiTGl1IiwiZ2l2ZW5fbmFtZSI6IlBlbmdmZWkiLCJncm91cHMiOlsicHJvamV0LW9ueXhpYSIsInJlbGV2YW5jIiwic3BhcmstbGFiIiwic3NwY2xvdWQtYWRtaW4iXSwiaWF0IjoxNjI4MDYyMDg3LCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoiMGZmYjc2YzEtYjBlMi00MjcwLThmZTItOGYwMGVkMjQ0ODMyIiwibG9jYWxlIjoiZnIiLCJuYW1lIjoiUGVuZ2ZlaSBMaXUiLCJub25jZSI6IjFhYjdiYWRlLWI0MzgtNDM4YS05OTVhLWEwZjJhYmU5M2RlZSIsInBvbGljeSI6IiIsInByZWZlcnJlZF91c2VybmFtZSI6InBlbmdmZWkiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiQXRsYXNfcm9sZV9hZG1pbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZ3JvdXBzIGVtYWlsIiwic2Vzc2lvbl9zdGF0ZSI6IjVkYTM1MzNkLTRjMGUtNDg0MC04YTEwLWMzM2Q5ZThlY2FhMyIsInN1YiI6IjQ3MzQ5MTI4LTRhNGMtNDIyNi1hNWIxLTY4MDgwMWFmNWEyYiIsInR5cCI6IkJlYXJlciJ9.mH5RNfwkKIL-vQfJ0B2gO6QnWIFB_0tIXIxGa_grTS6q6On4gvzgcsYi2bDHgRgvyePwqSptNYRYJ7aqc-ZgYQ"
      - name: aws-access-key
        value: "3Q5LXWDO28WQ3V9P4IYP"
      - name: mlflow-tracking-uri
        value: 'https://pengfei-mlflow-7841853311341079041-mlflow-ihm.kub.sspcloud.fr/'
      - name: mlflow-experiment-name
        value: "openfood"
      - name: mlflow-s3-url
        value: "https://minio.lab.sspcloud.fr"
      - name: model-training-conf-list
        value: |
          [
            { "lr": 2e-4, "nepochs": 1 },
            { "lr": 3e-4, "nepochs": 1 },
            { "lr": 4e-4, "nepochs": 1 },
            { "lr": 5e-4, "nepochs": 1 }
          ]
  # Create a pvc for the workflow
  volumeClaimTemplates:
    - metadata:
        name: workflow-tmp
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

  templates:
    #############################################################################################
    #################### main template for planning dag of the pipeline #########################
    #############################################################################################
    - name: main
      dag:
        tasks:
          # task 0: load code source and data
          - name: load-code-and-data
            template: load-code-and-data-wt
          # task 1: train model with given params
          - name: train-model-with-given-params
            dependencies: [ load-code-and-data ]
            template: run-model-training-wt
            arguments:
              parameters:
                - name: lr
                  value: "{{item.lr}}"
                - name: nepochs
                  value: "{{item.nepochs}}"
              # pass the inputs to the step "withParam"
            withParam: "{{workflow.parameters.model-training-conf-list}}"
    ####################################################################################################################
    #################### task template for implementing the logic of each task of the pipeline #########################
    ####################################################################################################################
    # worker template for task-0 load code
    - name: load-code-and-data-wt
      inputs:
        artifacts:
          # Check out the master branch of the argo repo and place it at /src
          # revision can be anything that git checkout accepts: branch, commit, tag, etc.
          - name: code
            path: /mnt/bin
            git:
              repo: https://github.com/pengfei99/openfood.git
              revision: "main"
      container:
        image: liupengfei99/openfood-cpu-worker:latest
        command: [ sh, -c ]
        args: [ "mkdir -p /mnt/openfood_data;
                 python /mnt/bin/siamesenetwork/main.py -c /mnt/bin/siamesenetwork/config.yml;
                 ls -l /mnt/bin /mnt/openfood_data" ]
        env:
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{workflow.parameters.aws-secret-access-key}}"
          - name: AWS_DEFAULT_REGION
            value: "{{workflow.parameters.aws-default-region}}"
          - name: AWS_S3_ENDPOINT
            value: "{{workflow.parameters.aws-s3-endpoint}}"
          - name: AWS_SESSION_TOKEN
            value: "{{workflow.parameters.aws-session-token}}"
          - name: AWS_ACCESS_KEY_ID
            value: "{{workflow.parameters.aws-access-key}}"
        volumeMounts:
          - name: workflow-tmp
            mountPath: /mnt

    # worker template for task-1 train model
    - name: run-model-training-wt
      inputs:
        parameters:
          - name: lr
          - name: nepochs
      container:
        image: liupengfei99/openfood-cpu-worker:latest
        command: [sh, -c]
        args: ["python /mnt/bin/siamesenetwork/run_pretrained_embedding_with_mlflow.py
                -c /mnt/bin/siamesenetwork/config.yml -n {{inputs.parameters.nepochs}} -l {{inputs.parameters.lr}}"]
        env:
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{workflow.parameters.aws-secret-access-key}}"
          - name: AWS_DEFAULT_REGION
            value: "{{workflow.parameters.aws-default-region}}"
          - name: AWS_S3_ENDPOINT
            value: "{{workflow.parameters.aws-s3-endpoint}}"
          - name: AWS_SESSION_TOKEN
            value: "{{workflow.parameters.aws-session-token}}"
          - name: AWS_ACCESS_KEY_ID
            value: "{{workflow.parameters.aws-access-key}}"
          - name: MLFLOW_TRACKING_URI
            value: "{{workflow.parameters.mlflow-tracking-uri}}"
          - name: MLFLOW_EXPERIMENT_NAME
            value: "{{workflow.parameters.mlflow-experiment-name}}"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "{{workflow.parameters.mlflow-s3-url}}"
        volumeMounts:
          - name: workflow-tmp
            mountPath: /mnt

